---

- name: Install alacritty mac
  community.general.homebrew_cask:
    name: alacritty
    greedy: true
  when: ansible_facts['os_family']|lower == 'darwin'
  tags:
    - alacritty

- name: alacritty linux deps
  shell:
    cmd: "sudo dnf install -y cmake freetype-devel fontconfig-devel libxcb-devel libxkbcommon-devel g++"
  when: ansible_facts['os_family']|lower == 'redhat'
  tags:
    - alacritty

- name: Check if we've cloned the alacritty repo
  ansible.builtin.stat:
    path: /tmp/alacritty
  register: p
  when: ansible_facts['os_family']|lower == 'redhat'
  tags:
    - alacritty

- name: Install alacritty linux
  shell: |
    cd /tmp
    git clone https://github.com/alacritty/alacritty.git
    cd alacritty

    cargo build --release
    sudo cp target/release/alacritty /usr/local/bin
    sudo cp extra/logo/alacritty-term.svg /usr/share/pixmaps/Alacritty.svg
    sudo desktop-file-install extra/linux/Alacritty.desktop
    sudo update-desktop-database
  when: ansible_facts['os_family']|lower == 'redhat' and not p.stat.isdir is defined
  tags:
    - alacritty

- name: Checkout dotfiles
  git:
    repo: 'https://github.com/johnwakley/dotfiles'
    dest: "{{ dotfile_path }}"
    update: false
  tags:
    - alacritty

- name: Create config folder
  file:
    path: "~/.config/alacritty"
    recurse: true
    state: directory
  tags:
    - alacritty

- name: Copy alacritty config to ~
  shell:
    cmd: 'cp {{ dotfile_path }}/alacritty.yml ~/.config/alacritty'
  tags:
    - alacritty
