---

# Prevent volta from updating .zshrc (https://docs.volta.sh/advanced/installers#skipping-volta-setup)
- name: Install volta
  shell:
    cmd: "curl https://get.volta.sh | bash -s -- --skip-setup"
  tags: [nodejs]

- name: Update nodejs version
  shell:
    cmd: "volta install node@{{ nodejs_version }}"
  tags: [nodejs]

- name: Install yarn
  shell:
    cmd: "volta install yarn"
  tags: [nodejs]

- name: Install watchman (mac)
  homebrew:
    name: watchman
    state: present
  when: ansible_facts['os_family']|lower == 'darwin'
  tags: [nodejs]

- name: Install watchman (linux)
  block:
    - name: Download watchman archive
      get_url:
        url: "{{ watchman_archive }}"
        dest: "/tmp/{{ watchman_rpm }}"
    - name: Extract watchman archive
      shell:
        cmd: 'sudo dnf localinstall -y /tmp/{{ watchman_rpm }}'
  when: ansible_facts['os_family']|lower == 'redhat'
  tags: [nodejs]
