---

- name: Install yq Mac
  shell: |
    sudo wget https://github.com/mikefarah/yq/releases/latest/download/yq_darwin_arm64 -O /usr/bin/yq &&\
      sudo chmod +x /usr/bin/yq
  when: ansible_facts['os_family']|lower == 'darwin'
  tags:
    - yq

- name: Install yq linux
  shell: |
    sudo wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/bin/yq &&\
      sudo chmod +x /usr/bin/yq
  when: ansible_facts['os_family']|lower == 'redhat'
  tags:
    - yq
