---

# https://docs.docker.com/engine/install/fedora/
- name: Install docker linux
  shell: |
    sudo dnf -y config-manager \
      --add-repo \
      https://download.docker.com/linux/fedora/docker-ce.repo
    sudo dnf -y install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin

    #
    # Post install (https://docs.docker.com/engine/install/linux-postinstall/)
    #

    # Join docker admin group
    sudo usermod -aG docker $USER

    # Run docker on start up
    sudo systemctl enable docker.service
    sudo systemctl enable containerd.service
  when: ansible_facts['os_family']|lower == 'redhat'
  tags:
    - docker
